// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-demo/order/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Login},
			[]rest.Route{
				{
					// 获取订单信息
					Method:  http.MethodPost,
					Path:    "/order/info",
					Handler: orderInfoHandler(serverCtx),
				},
			}...,
		),
	)
}
