// Code generated by goctl. DO NOT EDIT.
package types

type OrderInfoReq struct {
	OrderId int64 `json:"order_id"`
}

type OrderInfoResp struct {
	OrderId   int64  `json:"order_id"`   // 订单id
	GoodsName string `json:"goods_name"` // 商品名称
}
